services:
  redis:
    image: redis:6.2
    container_name: gosocket_redis_test
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10
